"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

export type Language = "en" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

export const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.journals": "Journals",
    "nav.trainings": "Trainings",
    "nav.resources": "Resources",
    "nav.forAuthors": "For Authors",
    "nav.policies": "Policies",
    "nav.editorialBoard": "Editorial Board",
    "nav.contact": "Contact",
    "nav.submitManuscript": "Submit Manuscript",
    "nav.authorGuidelines": "Author Guidelines",
    "nav.apcFees": "APC & Fees",
    "nav.aimsScope": "Aims & Scope",
    "nav.peerReview": "Peer Review Process",
    "nav.publicationEthics": "Publication Ethics",
    "nav.openAccess": "Open Access Policy",
    "nav.goldOA": "Gold Open Access",
    "nav.hybridOA": "Hybrid Open Access",
    
    // Brand
    "brand.name": "Scholarly Open",
    "brand.tagline": "Unbound. Transparent. Accessible.",
    "brand.description": "An international open-access publisher dedicated to advancing knowledge through rigorous peer review and open access.",
    
    // Hero Section
    "hero.title": "Advancing Knowledge Through Open Access",
    "hero.subtitle": "Scholarly Open is an international open-access publisher committed to disseminating high-quality research in Artificial Intelligence, Clinical Medicine, Environmental Science, Data Science, Engineering, and Social Sciences & Humanities through Gold open access.",
    "hero.cta.submit": "Submit Your Research",
    "hero.cta.learn": "Learn More",
    
    // Stats
    "stats.openAccess": "Open Access",
    "stats.journals": "Journals",
    "stats.reach": "Reach",
    "stats.guidelines": "Guidelines",
    
    // Journals Section
    "journals.title": "Our Journals",
    "journals.subtitle": "We publish high-quality research across our core disciplines and our new Emerging Frontiers Series, all offering Gold open access.",
    "journals.viewJournal": "View Journal",
    "journals.bio.title": "Scholarly Open: Biology",
    "journals.bio.description": "Experimental and translational biology spanning molecular, cellular, and systems research.",
    "journals.chem.title": "Scholarly Open: Chemistry",
    "journals.chem.description": "Research in chemical sciences, materials, catalysis, and sustainable chemical technologies.",
    "journals.med.title": "Scholarly Open: Medicine",
    "journals.med.description": "Clinical research, translational medicine, and healthcare innovations that advance patient outcomes.",
    "journals.ds.title": "Scholarly Open: Data Science",
    "journals.ds.description": "Data-driven research, AI-enabled analytics, statistical methods, and computational science.",
    "journals.eng.title": "Scholarly Open: Engineering",
    "journals.eng.description": "Applied engineering research across infrastructure, energy, robotics, and systems innovation.",
    "journals.env.title": "Scholarly Open: Environmental Science",
    "journals.env.description": "Interdisciplinary research in climate science, sustainability, ecosystems, and environmental policy.",
    "journals.ss.title": "Scholarly Open: Social Sciences & Humanities",
    "journals.ss.description": "Research in society, culture, behavior, policy, and interdisciplinary social science and humanities inquiry.",
    "journals.clinical-ai.title": "Scholarly Open: Clinical AI & Digital Health",
    "journals.clinical-ai.description": "Clinical applications of machine learning, digital health systems, and computational diagnostics.",
    "journals.ai-safety.title": "Scholarly Open: AI Safety & Governance",
    "journals.ai-safety.description": "Research on AI alignment, safety evaluations, policy frameworks, and algorithmic governance.",
    "journals.decarbonization.title": "Scholarly Open: Decarbonization & Carbon Tech",
    "journals.decarbonization.description": "Engineered climate solutions, carbon capture, utilization, storage, and net-zero technologies.",
    "journals.quantum-engineering.title": "Scholarly Open: Quantum Engineering",
    "journals.quantum-engineering.description": "Translation of quantum science into practical hardware, cryptography, and application architectures.",
    "journals.synthetic-biology.title": "Scholarly Open: Synthetic Biology & Bio-Design",
    "journals.synthetic-biology.description": "De novo bio-design, CRISPR therapeutics, cell-free biomanufacturing, and metabolic pathways.",
    "journals.space-resources.title": "Scholarly Open: Space Resources & Orbital Economy",
    "journals.space-resources.description": "In-situ lunar/asteroid resource utilization, space logistics, orbital debris, and space law.",
    
    // Features
    "features.title": "Why Publish With Us",
    "features.subtitle": "We combine academic rigor with modern publishing practices to maximize the impact of your research.",
    "features.openAccess.title": "Open Access",
    "features.openAccess.description": "All articles freely available to readers worldwide with no subscription barriers.",
    "features.peerReview.title": "Rigorous Peer Review",
    "features.peerReview.description": "Expert-led double-blind peer review ensuring the highest quality standards.",
    "features.rapidPublication.title": "Rapid Publication",
    "features.rapidPublication.description": "Efficient editorial process with fast turnaround from submission to publication.",
    "features.editorialBoard.title": "International Editorial Board",
    "features.editorialBoard.description": "Distinguished scholars from leading institutions across the globe.",
    
    // Open Access Models
    "oaModels.title": "Open Access Publishing",
    "oaModels.subtitle": "Publishing Model",
    "oaModels.description": "We publish open access journals with immediate, permanent availability under Creative Commons licensing.",
    "oaModels.gold.title": "Gold Open Access",
    "oaModels.gold.description": "All articles are immediately and permanently free to access upon publication under a Creative Commons license.",
    "oaModels.hybrid.title": "Creative Commons Licensing",
    "oaModels.hybrid.description": "Clear reuse rights with standard open licenses (e.g., CC BY 4.0) to maximize distribution and impact.",
    "oaModels.learnMore": "Learn About Our OA Policy",
    "oaModels.accessible": "Making research accessible to all",
    "oaModels.fromMainz": "Connecting researchers worldwide",
    
    // CTA Section
    "cta.title": "Ready to Share Your Research?",
    "cta.subtitle": "Join researchers worldwide who trust Scholarly Open to publish their work with integrity and impact.",
    "cta.submit": "Submit Manuscript",
    "cta.guidelines": "Author Guidelines",
    
    // Footer
    "footer.journals": "Journals",
    "footer.forAuthors": "For Authors",
    "footer.aboutUs": "About Us",
    "footer.policies": "Policies",
    "footer.copyright": "Scholarly Open i.G. All rights reserved.",
    "footer.ccbyStatement": "All content is published under CC BY 4.0.",
    "footer.privacy": "Privacy Policy",
    "footer.impressum": "Impressum",
    "footer.archiving": "Archiving & Indexing",
    
    // Compliance
    "compliance.title": "Compliance & Standards",
    "compliance.doaj": "DOAJ Guidelines",
    "compliance.cope": "Publication Ethics (COPE)",
    "compliance.crossref": "CrossRef Member",
    "compliance.ccby": "CC BY 4.0 License",
    "compliance.issn": "ISSN Registered",
    "compliance.oaspa": "OASPA Member",
    
    // Editorial Board
    "editorial.title": "Editorial Board",
    "editorial.subtitle": "Our distinguished editorial board comprises leading scholars from renowned institutions worldwide, ensuring the highest standards of peer review and editorial excellence.",
    "editorial.editorInChief": "Editor-in-Chief",
    "editorial.seniorEditors": "Senior Editors",
    "editorial.seniorEditorsSubtitle": "Our senior editors lead the editorial direction for each of our core disciplines.",
    "editorial.boardMembers": "Editorial Board Members",
    "editorial.boardMembersSubtitle": "Our editorial board members bring diverse expertise from institutions around the world.",
    "editorial.joinTeam": "Join Our Editorial Team",
    "editorial.joinTeamSubtitle": "We are always looking for distinguished scholars to join our editorial board. If you are interested in contributing to the advancement of open access, we would love to hear from you.",
    "editorial.expressInterest": "Express Interest",
    "editorial.discipline.socialSciences": "Social Sciences & Humanities",
    "editorial.discipline.archaeology": "Archaeology",
    "editorial.discipline.medicalSciences": "Medical Sciences",
    "editorial.editorInChief.role": "Editor-in-Chief",
    "editorial.editorInChief.specialization": "Social Sciences & Research Methodology",
    "editorial.senior1.role": "Senior Editor, Social Sciences & Humanities",
    "editorial.senior1.specialization": "Political Science & International Relations",
    "editorial.senior2.role": "Senior Editor, Archaeology",
    "editorial.senior2.specialization": "Classical Archaeology & Cultural Heritage",
    "editorial.senior3.role": "Senior Editor, Medical Sciences",
    "editorial.senior3.specialization": "Public Health & Epidemiology",
    "editorial.member.soc1.specialization": "Sociology & Social Policy",
    "editorial.member.soc2.specialization": "Economics & Development Studies",
    "editorial.member.soc3.specialization": "Psychology & Behavioral Sciences",
    "editorial.member.soc4.specialization": "Anthropology & Migration Studies",
    "editorial.member.arc1.specialization": "Prehistoric Archaeology",
    "editorial.member.arc2.specialization": "Archaeological Science & Dating Methods",
    "editorial.member.arc3.specialization": "Near Eastern Archaeology",
    "editorial.member.arc4.specialization": "Medieval Archaeology",
    "editorial.member.med1.specialization": "Clinical Medicine & Diagnostics",
    "editorial.member.med2.specialization": "Infectious Diseases",
    "editorial.member.med3.specialization": "Biomedical Research",
    "editorial.member.med4.specialization": "Pharmaceutical Sciences",
    
    // About Page
    "about.title": "About Scholarly Open",
    "about.subtitle": "Scholarly Open is an international open-access publisher dedicated to advancing knowledge through rigorous peer review and open access.",
    
    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our editorial team.",
    
    // Articles
    "articles.title": "Articles",
    "articles.latest": "Latest Articles",
    "articles.sampleTitle": "Sample Articles",
    "articles.sampleNote": "These article outlines are illustrative examples for our launch journals.",
    "articles.viewAll": "View All Articles",
    "articles.readMore": "Read More",
    "articles.published": "Published",
    "articles.doi": "DOI",
    "articles.keywords": "Keywords",
    "articles.abstract": "Abstract",
    "articles.fullText": "Full Text",
    "articles.pdf": "Download PDF",
    "articles.cite": "Cite",
    
    // Journal Page
    "journal.about": "About the Journal",
    "journal.aboutText": "Scholarly Open publishes highly relevant and FAIR-aligned research across our journals. We focus on transparent processes, rapid dissemination, and strong author support.",
    "journal.scope": "Scope & Coverage",
    "journal.sections": "Journal Sections",
    "journal.submitTo": "Submit to",
    "journal.submitText": "Please review our author guidelines and prepare your manuscript according to our submission requirements. We welcome original research, reviews, and methodological contributions that support FAIR scholarship.",
    "journal.startSubmission": "Start Submission",
    
    // About Page Content
    "about.heroTitle": "About Scholarly Open",
    "about.heroSubtitle": "We are an international open-access publisher committed to advancing scholarly communication through innovative publishing practices and unwavering commitment to research integrity.",
    "about.ourMission": "Our Mission",
    "about.missionTitle": "Democratizing Knowledge",
    "about.missionP1": "Our mission is to facilitate the global dissemination of high-quality research by providing open access to peer-reviewed scholarly articles. We believe that knowledge should not be constrained by financial or geographical barriers.",
    "about.missionP2": "We work with researchers, institutions, and funders worldwide to ensure that important discoveries in Artificial Intelligence, Clinical Medicine, Sustainability, Data Science, and Engineering reach the audiences who need them most.",
    "about.ourVision": "Our Vision",
    "about.visionTitle": "A More Open Future",
    "about.visionP1": "We envision a world where all scholarly research is freely accessible, where researchers are recognized for their contributions, and where the advancement of human knowledge benefits everyone equally.",
    "about.visionP2": "Through continuous innovation in publishing technology and processes, we strive to create a sustainable and equitable publishing ecosystem that serves the global research community.",
    
    "about.valuesTitle": "Our Core Values",
    "about.valuesSub": "These principles guide everything we do at Scholarly Open.",
    "about.value1.title": "Integrity",
    "about.value1.desc": "We uphold the highest ethical standards in scholarly publishing, ensuring transparency and accountability in all our processes.",
    "about.value2.title": "Openness",
    "about.value2.desc": "We believe knowledge should be freely accessible to all, breaking down barriers to scientific and scholarly information.",
    "about.value3.title": "Excellence",
    "about.value3.desc": "We are committed to publishing only the highest quality research through rigorous peer review and editorial oversight.",
    "about.value4.title": "Global Impact",
    "about.value4.desc": "We connect researchers across borders, fostering international collaboration and knowledge exchange.",

    "about.journeyTitle": "Our Journey",
    "about.journeySub": "Scholarly Open is a new publishing initiative. We are currently building our journal portfolio, refining our processes, and preparing our first open access publications.",
    "about.time1.title": "Foundation",
    "about.time1.desc": "Scholarly Open was established with a vision to transform scholarly publishing.",
    "about.time2.title": "Building Our Team",
    "about.time2.desc": "We assembled an editorial team, advisory board, and publishing partners to launch our journal portfolio.",
    "about.time3.title": "Developing Workflows",
    "about.time3.desc": "We are putting in place FAIR workflows, open access processes, and author support systems.",
    "about.time4.title": "Preparing for Launch",
    "about.time4.desc": "Our first journals are being prepared for publication, with compliance and indexing efforts underway.",

    "about.reachTitle": "Serving Researchers Worldwide",
    "about.reachP1": "Scholarly Open is dedicated to connecting researchers across the globe. We work with authors, reviewers, and institutions from every continent to advance scholarly communication.",
    "about.reachP2": "Our international editorial board and global network of peer reviewers ensure that research from all regions receives the attention and rigorous evaluation it deserves.",
    "about.communityTitle": "Join Our Community",
    "about.communitySub": "Whether as an author, reviewer, or editorial board member, we welcome your participation in advancing open scholarship.",
    "about.communitySubmit": "Submit Your Research",
    
    // Contact Page Content
    "contact.heroTitle": "Contact Us",
    "contact.heroSubtitle": "Have questions about submitting your research, our peer review process, or open access policies? Our team is here to help.",
    "contact.info.general": "General Inquiries",
    "contact.info.editorial": "Editorial Office",
    "contact.info.submissions": "Submissions",
    "contact.info.address": "Address",
    "contact.info.headquarters": "Headquarters",
    "contact.info.phone": "Main Office",
    "contact.info.hours": "Office Hours",
    "contact.info.weekday": "Monday - Friday",
    "contact.info.weekend": "Saturday - Sunday",
    "contact.info.weekendVal": "Closed",
    
    "contact.deptsTitle": "Department Contacts",
    "contact.deptsSub": "For faster response, please contact the appropriate department directly.",
    "contact.dept1.desc": "For manuscript-related inquiries, peer review questions, and editorial decisions.",
    "contact.dept2.desc": "For submission assistance, formatting questions, and author guidelines.",
    "contact.dept3.name": "Finance & APCs",
    "contact.dept3.desc": "For invoices, payment inquiries, and APC waiver requests.",
    "contact.dept4.name": "Technical Support",
    "contact.dept4.desc": "For website issues, submission system problems, and technical questions.",
    "contact.dept5.name": "Research Integrity & Ethics",
    "contact.dept5.desc": "For reporting ethical concerns, plagiarism allegations, or publication integrity issues.",

    "contact.form.title": "Send Us a Message",
    "contact.form.subtitle": "Fill out the form below and we will get back to you within 1-2 business days.",
    "contact.form.faqHeader": "Before contacting us, you might find answers in:",
    "contact.faq.ethicsDesc": "COPE compliance, research integrity guidelines, and ethics reporting.",
    "contact.form.cardTitle": "Contact Form",
    "contact.form.cardSub": "All fields marked with * are required.",
    "contact.form.sentTitle": "Message Sent",
    "contact.form.sentDesc": "Thank you for contacting us. We will respond within 1-2 business days.",
    "contact.form.sentButton": "Send Another Message",
    
    "contact.form.labelName": "Full Name *",
    "contact.form.labelEmail": "Email Address *",
    "contact.form.labelAffiliation": "Institution / Organization",
    "contact.form.labelSubject": "Subject *",
    "contact.form.labelMessage": "Message *",
    
    "contact.form.optDefault": "Select a subject",
    "contact.form.optSubmission": "Manuscript Submission",
    "contact.form.optReview": "Peer Review Status",
    "contact.form.optAPC": "APC / Payment",
    "contact.form.optTechnical": "Technical Issue",
    "contact.form.optEditorial": "Editorial Board",
    "contact.form.optEthics": "Research Integrity & Ethics Concerns",
    "contact.form.optPartner": "Partnership / Collaboration",
    "contact.form.optOther": "Other",
    
    "contact.form.privacyConsent": "I consent to the processing of my personal data for the purpose of handling my inquiry.",
    "contact.form.privacyRead": "I have read and agree to the",
    "contact.form.buttonSend": "Send Message",
    "contact.form.buttonSending": "Sending...",
    
    "contact.map.title": "Global Reach",
    "contact.map.subtitle": "Scholarly Open serves researchers worldwide, connecting scholars across all continents.",
    "contact.map.basedIn": "Based in Mainz, Germany",

    // Guidelines Page Extra
    "guidelines.heroTitle": "Author Guidelines",
    "guidelines.heroSubtitle": "Comprehensive instructions for preparing your manuscript for submission to Scholarly Open journals. Following these guidelines will help ensure a smooth review process across social sciences & humanities, medical, and other discipline-specific journals.",
    "guidelines.downloadTemplate": "Download Template",
    "guidelines.beforeSubmit": "Before You Submit",
    "guidelines.beforeSubmitSub": "Please ensure your submission meets these requirements before submitting.",
    "guidelines.originalWork": "Original Work",
    "guidelines.originalWorkDesc": "The manuscript must be original and not under consideration elsewhere. Plagiarism checks will be performed.",
    "guidelines.authorAgreement": "Author Agreement",
    "guidelines.authorAgreementDesc": "All authors must agree to the submission and meet ICMJE authorship criteria.",
    "guidelines.ethicsApproval": "Ethics Approval",
    "guidelines.ethicsApprovalDesc": "Research involving human subjects or animals must have appropriate ethics approval.",
    "guidelines.conflictOfInterest": "Conflict of Interest",
    "guidelines.conflictOfInterestDesc": "All potential conflicts of interest must be disclosed in the manuscript.",

    // APC Page
    "apc.heroSubtitle": "Transparent pricing for open access publication. We offer competitive APCs with waiver programs to ensure research from all backgrounds can be published.",
    "apc.understandingTitle": "Understanding APCs",
    "apc.understandingDesc": "Article Processing Charges (APCs) are fees charged to authors or their institutions to cover the costs of open access publication. APCs allow us to make articles freely available to readers worldwide while maintaining high editorial and production standards.",
    "apc.chargedTitle": "When is the APC charged?",
    "apc.chargedDesc": "APCs are only charged after your manuscript has been accepted for publication following peer review. There are no submission or review fees.",
    "apc.coversTitle": "What does the APC cover?",
    "apc.coversDesc": "The APC covers peer review management, copyediting, typesetting, DOI registration, hosting, archiving, and ongoing accessibility.",
    "apc.whoPaysTitle": "Who pays the APC?",
    "apc.whoPaysDesc": "APCs can be paid by authors, their institutions, research funders, or through institutional agreements. Many funders allow APCs as legitimate research costs.",
    "apc.currentRatesTitle": "Current APC Rates",
    "apc.currentRatesDesc": "Our APCs vary by discipline to reflect the different costs and services involved. These rates apply across our portfolio of seven Scholarly Open journals.",
    "apc.perArticle": "per article",
    "apc.vatNotice": "All prices exclude VAT where applicable. Institutional agreements may provide different rates.",
    "apc.waiversTitle": "Fee Waivers & Discounts",
    "apc.waiversDesc": "We are committed to making open access publishing accessible to researchers worldwide, regardless of their financial situation.",
    "apc.applyWaiverTitle": "How to Apply for a Waiver",
    "apc.applyWaiverDesc": "Waiver requests should be made at the time of submission through our online submission system. Please provide details about your funding situation and eligibility category. Waiver decisions are made independently of editorial decisions and will not affect the peer review process.",
    "apc.paymentTitle": "Payment Methods",
    "apc.paymentDesc": "We offer flexible payment options to accommodate different institutional requirements.",
    "apc.creditCard": "Credit Card",
    "apc.creditCardDesc": "Visa, Mastercard, and American Express accepted through our secure payment portal.",
    "apc.bankTransfer": "Bank Transfer",
    "apc.bankTransferDesc": "Invoice payment via SEPA or international wire transfer. Bank details provided upon acceptance.",
    "apc.instAgreements": "Institutional Agreements",
    "apc.instAgreementsDesc": "Check if your institution has an agreement with us for centralized billing.",
    "apc.complianceTitle": "Funder Compliance",
    "apc.complianceDesc": "Our open access policies comply with major research funder mandates.",
    "apc.questionsTitle": "Questions About Fees?",
    "apc.questionsDesc": "Our team is happy to discuss payment options, waivers, or institutional agreements.",

    // Open Access Page
    "openaccess.heroSubtitle": "Scholarly Open is committed to open access publishing. We believe that scientific knowledge should be freely available to everyone, everywhere, to accelerate research and benefit society.",
    "openaccess.aboutOATitle": "About Open Access",
    "openaccess.aboutOASubtitle": "Knowledge Without Barriers",
    "openaccess.aboutOAP1": "Open access (OA) means that research outputs are distributed online, free of cost and free of most copyright and licensing restrictions. Anyone can read, download, copy, distribute, print, search, or link to the full text of these articles.",
    "openaccess.aboutOAP2": "We support the principles of the Budapest Open Access Initiative (2002) and believe that removing access barriers to scholarly literature accelerates research, enriches education, and enables new forms of collaboration.",
    "openaccess.freeToRead": "Free to Read",
    "openaccess.freeToReuse": "Free to Reuse",
    "openaccess.freeToShare": "Free to Share",
    "openaccess.benefitsTitle": "Benefits of Open Access",
    "openaccess.benefitsDesc": "Open access publishing offers significant advantages for authors, readers, and society.",
    "openaccess.benefit1.title": "Global Reach",
    "openaccess.benefit1.desc": "Open access articles reach a wider audience, including researchers, practitioners, policymakers, and the general public worldwide.",
    "openaccess.benefit2.title": "Increased Citations",
    "openaccess.benefit2.desc": "Studies show that open access articles receive more citations and have greater research impact than subscription-only content.",
    "openaccess.benefit3.title": "Immediate Access",
    "openaccess.benefit3.desc": "Research is available immediately upon publication with no embargo period, accelerating the pace of scientific discovery.",
    "openaccess.benefit4.title": "Public Benefit",
    "openaccess.benefit4.desc": "Publicly funded research becomes publicly available, maximizing the societal return on investment in science.",
    "openaccess.modelTitle": "Our Open Access Model",
    "openaccess.modelDesc": "All Scholarly Open journals publish using a Gold open access model, ensuring every article is freely available from the moment it is published.",
    "openaccess.goldBadge": "Standard Model",
    "openaccess.goldDesc": "All Scholarly Open journals publish immediately open access under a Creative Commons license. The author or their institution pays an Article Processing Charge (APC) to cover publication costs.",
    "openaccess.goldFeature1": "Immediate open access upon publication",
    "openaccess.goldFeature2": "CC BY 4.0 license by default",
    "openaccess.goldFeature3": "Full copyright retained by authors",
    "openaccess.goldFeature4": "Indexed in major databases",
    "openaccess.goldFeature5": "Permanent free access",
    "openaccess.licensingTitle": "Licensing",
    "openaccess.licensingDesc": "We use Creative Commons licenses to define how published content can be reused, ensuring clarity for both authors and readers.",
    "openaccess.ccbyDefault": "CC BY 4.0 (Default)",
    "openaccess.ccbyDefaultDesc": "This license allows others to distribute, remix, adapt, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating license offered and is recommended for maximum dissemination.",
    "openaccess.ccbync": "CC BY-NC 4.0",
    "openaccess.ccbyncDesc": "Similar to CC BY, but limits reuse to non-commercial purposes. Available upon request in specific circumstances.",
    "openaccess.ccbyncnd": "CC BY-NC-ND 4.0",
    "openaccess.ccbyncndDesc": "The most restrictive license, allowing only non-commercial redistribution with no derivatives. Available in exceptional cases.",
    "openaccess.rightsTitle": "Author Rights",
    "openaccess.rightsDesc": "At Scholarly Open, authors retain copyright of their work. Here's what this means for you:",
    "openaccess.right1.title": "Copyright Retention",
    "openaccess.right1.desc": "Authors retain full copyright ownership of their work. We only request a license to publish.",
    "openaccess.right2.title": "Self-Archiving",
    "openaccess.right2.desc": "Authors may deposit the published version in institutional repositories and other platforms immediately upon publication.",
    "openaccess.right3.title": "Reuse",
    "openaccess.right3.desc": "Authors may reuse their work in future publications, presentations, and teaching materials without seeking permission.",
    "openaccess.right4.title": "Third-Party Permissions",
    "openaccess.right4.desc": "For figures or text from third-party sources, authors are responsible for obtaining appropriate permissions.",
    "openaccess.complianceTitle": "Funder Compliance",
    "openaccess.complianceDesc": "Our open access policies are designed to comply with the requirements of major research funders.",
    "openaccess.complianceNote": "If your funder has specific requirements not listed here, please contact us to discuss compliance options.",
    "openaccess.ctaTitle": "Publish Open Access With Us",
    "openaccess.ctaSubtitle": "Join the open access movement and make your research freely available to the world.",
    "openaccess.ctaSubmit": "Submit Your Research",
    "openaccess.ctaApc": "View APC Information",

    // Privacy Page
    "privacy.heroSubtitle": "This privacy policy explains how Scholarly Open collects, uses, and protects your personal data in accordance with the General Data Protection Regulation (GDPR) and German data protection laws.",
    "privacy.lastUpdated": "Last updated: January 2024",
    "privacy.controller.title": "1. Data Controller",
    "privacy.controller.desc": "The data controller responsible for processing your personal data is:",
    "privacy.controller.addr": "Scholarly Open\nInternational Open Access Publisher\nEmail: info@scholarlyopen.org",
    "privacy.data.title": "2. Data We Collect",
    "privacy.data.desc": "We collect and process the following categories of personal data:",
    "privacy.data.provide.title": "2.1 Information You Provide",
    "privacy.data.provide.li1": "Name, email address, and institutional affiliation when creating an account",
    "privacy.data.provide.li2": "Manuscript submissions and associated author information",
    "privacy.data.provide.li3": "Correspondence with our editorial team",
    "privacy.data.provide.li4": "Payment information for Article Processing Charges",
    "privacy.data.provide.li5": "Reviewer reports and editorial communications",
    "privacy.data.auto.title": "2.2 Automatically Collected Information",
    "privacy.data.auto.li1": "IP address and browser information",
    "privacy.data.auto.li2": "Pages visited and time spent on our website",
    "privacy.data.auto.li3": "Referring website information",
    "privacy.data.auto.li4": "Device type and operating system",
    "privacy.data.basis.title": "3. Legal Basis for Processing",
    "privacy.data.basis.desc": "We process your personal data based on the following legal grounds under GDPR Article 6:",
    "privacy.data.basis.li1": "Contract performance (Art. 6(1)(b)): Processing necessary to fulfill our publishing services",
    "privacy.data.basis.li2": "Legitimate interests (Art. 6(1)(f)): Improving our services and website functionality",
    "privacy.data.basis.li3": "Legal obligations (Art. 6(1)(c)): Compliance with tax and record-keeping requirements",
    "privacy.data.basis.li4": "Consent (Art. 6(1)(a)): Marketing communications and optional cookies",
    "privacy.use.title": "4. How We Use Your Data",
    "privacy.use.desc": "Your personal data is used for the following purposes:",
    "privacy.use.li1": "Processing and managing manuscript submissions",
    "privacy.use.li2": "Communicating about the peer review process",
    "privacy.use.li3": "Publishing articles and maintaining the scholarly record",
    "privacy.use.li4": "Processing payments and issuing invoices",
    "privacy.use.li5": "Sending service-related notifications",
    "privacy.use.li6": "Improving our website and services",
    "privacy.use.li7": "Complying with legal and regulatory requirements",
    "privacy.sharing.title": "5. Data Sharing",
    "privacy.sharing.desc": "We may share your personal data with:",
    "privacy.sharing.li1": "Peer reviewers: Anonymized manuscript content for review",
    "privacy.sharing.li2": "Indexing services: Published article metadata",
    "privacy.sharing.li3": "Payment processors: For secure payment processing",
    "privacy.sharing.li4": "Service providers: Hosting, email, and analytics services",
    "privacy.sharing.li5": "Legal authorities: When required by law",
    "privacy.sharing.noSell": "We do not sell your personal data to third parties.",
    "privacy.transfers.title": "6. International Data Transfers",
    "privacy.transfers.desc": "Some of our service providers may be located outside the European Economic Area (EEA). When we transfer data outside the EEA, we ensure appropriate safeguards are in place, including:",
    "privacy.transfers.li1": "EU Standard Contractual Clauses",
    "privacy.transfers.li2": "Adequacy decisions by the European Commission",
    "privacy.transfers.li3": "Binding Corporate Rules where applicable",
    "privacy.retention.title": "7. Data Retention",
    "privacy.retention.desc": "We retain your personal data for as long as necessary to fulfill the purposes for which it was collected:",
    "privacy.retention.li1": "Published articles: Permanently (part of the scholarly record)",
    "privacy.retention.li2": "Account information: Duration of account plus 3 years",
    "privacy.retention.li3": "Rejected manuscripts: 2 years after rejection",
    "privacy.retention.li4": "Financial records: 10 years (German tax law requirement)",
    "privacy.retention.li5": "Website analytics: 26 months",
    "privacy.rights.title": "8. Your Rights",
    "privacy.rights.desc": "Under GDPR, you have the following rights regarding your personal data:",
    "privacy.rights.li1": "Access: Request a copy of your personal data",
    "privacy.rights.li2": "Rectification: Correct inaccurate or incomplete data",
    "privacy.rights.li3": "Erasure: Request deletion of your data (with limitations)",
    "privacy.rights.li4": "Restriction: Limit processing of your data",
    "privacy.rights.li5": "Portability: Receive your data in a structured format",
    "privacy.rights.li6": "Objection: Object to processing based on legitimate interests",
    "privacy.rights.li7": "Withdraw consent: Where processing is based on consent",
    "privacy.rights.contact": "To exercise these rights, please contact us at privacy@scholarlyopen.org.",
    "privacy.cookies.title": "9. Cookies",
    "privacy.cookies.desc1": "We use cookies and similar technologies on our website. Essential cookies are necessary for the website to function. Analytics and preference cookies are only used with your consent.",
    "privacy.cookies.desc2": "You can manage your cookie preferences through our cookie banner or your browser settings.",
    "privacy.security.title": "10. Security",
    "privacy.security.desc": "We implement appropriate technical and organizational measures to protect your personal data, including:",
    "privacy.security.li1": "Encryption of data in transit and at rest",
    "privacy.security.li2": "Access controls and authentication",
    "privacy.security.li3": "Regular security assessments",
    "privacy.security.li4": "Staff training on data protection",
    "privacy.complaints.title": "11. Complaints",
    "privacy.complaints.desc": "If you believe we have not handled your personal data correctly, you have the right to lodge a complaint with a supervisory authority in your jurisdiction. Please contact us at privacy@scholarlyopen.org and we will assist you in identifying the appropriate authority.",
    "privacy.changes.title": "12. Changes to This Policy",
    "privacy.changes.desc": "We may update this privacy policy from time to time. We will notify you of significant changes by posting a notice on our website or sending you an email.",
    "privacy.contact.title": "13. Contact Us",
    "privacy.contact.desc": "If you have any questions about this privacy policy or our data practices, please contact:",
    "privacy.contact.addr": "Data Protection Officer\nScholarly Open\nEmail: info@scholarlyopen.org",

    // Impressum Page
    "impressum.heroSubtitle": "Legal notice in accordance with Section 5 TMG (German Telemedia Act) and Section 55 RStV (German Interstate Broadcasting Treaty).",
    "impressum.warningTitle": "Gründungsphase (i.G.) / Founding Phase",
    "impressum.warningDesc1": "Scholarly Open befindet sich derzeit in der Gründungsphase (in Gründung / i.G.). Die formelle Eintragung ins Handelsregister sowie die Beantragung der Umsatzsteuer-Identifikationsnummer erfolgen nach Abschluss der organisatorischen Aufbauphase. Bis zur vollständigen Registrierung sind die unten genannten Personen gemeinsam verantwortlich.",
    "impressum.warningDesc2": "Scholarly Open is currently in the founding phase (in Gründung / i.G.). Formal registration in the commercial register and application for the VAT identification number will take place after the organizational setup phase is completed. Until full registration, the persons named below are jointly responsible for the content.",
    "impressum.tmgTitle": "Angaben gemäß § 5 TMG",
    "impressum.tmgCompany": "Scholarly Open i.G.",
    "impressum.tmgPhase": "(in Gründung / under formation)",
    "impressum.tmgPub": "International Open Access Publisher",
    "impressum.ownersTitle": "Verantwortliche Personen / Responsible Persons",
    "impressum.ownerRole": "Inhaber und verantwortlich für den gesamten Inhalt",
    "impressum.ownerRoleSub": "(Owner and responsible for all content)",
    "impressum.contactTitle": "Kontakt / Contact",
    "impressum.contactEmail": "E-Mail:",
    "impressum.contactWebsite": "Website:",
    "impressum.statusTitle": "Registrierungsstatus / Registration Status",
    "impressum.statusHR": "Handelsregistereintragung:",
    "impressum.statusHRSub": "In Vorbereitung. Die Eintragung erfolgt nach Abschluss der Gründungsphase. (Commercial register entry: In preparation. Registration will be completed after the founding phase.)",
    "impressum.statusVat": "Umsatzsteuer-ID:",
    "impressum.statusVatSub": "Wird nach der Gewerbeanmeldung beim zuständigen Finanzamt beantragt. (VAT ID: Will be applied for at the responsible tax office after business registration.)",
    "impressum.rstvTitle": "Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV",
    "impressum.disputeTitle": "EU-Streitschlichtung",
    "impressum.disputeDesc1": "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:",
    "impressum.disputeDesc2": "Unsere E-Mail-Adresse finden Sie oben im Impressum.",
    "impressum.consumerTitle": "Verbraucherstreitbeilegung / Universalschlichtungsstelle",
    "impressum.consumerDesc": "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.",
    "impressum.liabContentTitle": "Haftung für Inhalte",
    "impressum.liabContentDesc1": "Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.",
    "impressum.liabContentDesc2": "Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.",
    "impressum.liabLinksTitle": "Haftung für Links",
    "impressum.liabLinksDesc1": "Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.",
    "impressum.liabLinksDesc2": "Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.",
    "impressum.copyrightTitle": "Urheberrecht",
    "impressum.copyrightDesc1": "Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.",
    "impressum.copyrightDesc2": "Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.",
    "impressum.copyrightDesc3": "Hinweis: Die in unseren Zeitschriften veröffentlichten Artikel unterliegen den jeweiligen Creative Commons Lizenzen und können entsprechend der Lizenzbedingungen weiterverwendet werden.",

    // Language Toggle
    "language.en": "English",
    "language.de": "Deutsch",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.about": "Über uns",
    "nav.journals": "Zeitschriften",
    "nav.trainings": "Schulungen",
    "nav.resources": "Ressourcen",
    "nav.forAuthors": "Für Autoren",
    "nav.policies": "Richtlinien",
    "nav.editorialBoard": "Redaktionsbeirat",
    "nav.contact": "Kontakt",
    "nav.submitManuscript": "Manuskript einreichen",
    "nav.authorGuidelines": "Autorenrichtlinien",
    "nav.apcFees": "APC & Gebühren",
    "nav.aimsScope": "Ziele & Umfang",
    "nav.peerReview": "Peer-Review-Verfahren",
    "nav.publicationEthics": "Publikationsethik",
    "nav.openAccess": "Open-Access-Richtlinie",
    "nav.goldOA": "Gold Open Access",
    "nav.hybridOA": "Hybrid Open Access",
    
    // Brand
    "brand.name": "Scholarly Open",
    "brand.tagline": "Ungebunden. Transparent. Zugänglich.",
    "brand.description": "Ein internationaler Open-Access-Verlag, der sich der Förderung von Wissen durch rigoroses Peer-Review und offenen Zugang verschrieben hat.",
    
    // Hero Section
    "hero.title": "Wissen fördern durch Open Access",
    "hero.subtitle": "Scholarly Open ist ein internationaler Open-Access-Verlag, der sich der Verbreitung hochwertiger Forschung in den Bereichen Künstliche Intelligenz, Klinische Medizin, Umweltwissenschaften, Data Science, Ingenieurwesen und Sozial- & Geisteswissenschaften durch Gold-Open-Access verschrieben hat.",
    "hero.cta.submit": "Ihre Forschung einreichen",
    "hero.cta.learn": "Mehr erfahren",
    
    // Stats
    "stats.openAccess": "Open Access",
    "stats.journals": "Zeitschriften",
    "stats.reach": "Reichweite",
    "stats.guidelines": "Richtlinien",
    
    // Journals Section
    "journals.title": "Unsere Zeitschriften",
    "journals.subtitle": "Wir veröffentlichen hochwertige Forschung in unseren Kerndisziplinen und unserer neuen Serie 'Emerging Frontiers' mit vollständigem Gold-Open-Access.",
    "journals.viewJournal": "Zeitschrift ansehen",
    "journals.bio.title": "Scholarly Open: Biology",
    "journals.bio.description": "Experimentelle und translationale Biologie von molekularer bis systemischer Ebene.",
    "journals.chem.title": "Scholarly Open: Chemistry",
    "journals.chem.description": "Forschung in Chemie, Materialien, Katalyse und nachhaltiger Chemietechnik.",
    "journals.med.title": "Scholarly Open: Medicine",
    "journals.med.description": "Klinische Forschung, translationale Medizin und Innovationen im Gesundheitswesen.",
    "journals.ds.title": "Scholarly Open: Data Science",
    "journals.ds.description": "Datengetriebene Forschung, KI-gestützte Analytik, Statistik und rechnergestützte Wissenschaft.",
    "journals.eng.title": "Scholarly Open: Engineering",
    "journals.eng.description": "Angewandte Ingenieurswissenschaften in Infrastruktur, Energie, Robotik und Systeminnovation.",
    "journals.env.title": "Scholarly Open: Environmental Science",
    "journals.env.description": "Interdisziplinäre Forschung zu Klima, Nachhaltigkeit, Ökosystemen und Umweltpolitik.",
    "journals.ss.title": "Scholarly Open: Social Sciences & Humanities",
    "journals.ss.description": "Forschung zu Gesellschaft, Kultur, Verhalten, Politik sowie interdisziplinären Sozial- und Geisteswissenschaften.",
    "journals.clinical-ai.title": "Scholarly Open: Clinical AI & Digital Health",
    "journals.clinical-ai.description": "Klinische Anwendungen des maschinellen Lernens, digitale Gesundheitssysteme und computergestützte Diagnostik.",
    "journals.ai-safety.title": "Scholarly Open: AI Safety & Governance",
    "journals.ai-safety.description": "Forschung zu KI-Ausrichtung, Sicherheitsbewertungen, politischen Rahmenbedingungen und algorithmischer Governance.",
    "journals.decarbonization.title": "Scholarly Open: Decarbonization & Carbon Tech",
    "journals.decarbonization.description": "Klimatechnische Lösungen, CO2-Abscheidung, -Nutzung, -Speicherung und Netto-Null-Technologien.",
    "journals.quantum-engineering.title": "Scholarly Open: Quantum Engineering",
    "journals.quantum-engineering.description": "Umsetzung der Quantenwissenschaft in praktische Hardware, Kryptographie und Anwendungsarchitekturen.",
    "journals.synthetic-biology.title": "Scholarly Open: Synthetic Biology & Bio-Design",
    "journals.synthetic-biology.description": "De-novo-Biodesign, CRISPR-Therapeutika, zellfreie Biomanufaktur und Stoffwechselwege.",
    "journals.space-resources.title": "Scholarly Open: Space Resources & Orbital Economy",
    "journals.space-resources.description": "In-situ-Nutzung von Mond- und Asteroidenressourcen, Weltraumlogistik, Weltraummüll und Weltraumrecht.",
    
    // Features
    "features.title": "Warum bei uns veröffentlichen",
    "features.subtitle": "Wir verbinden akademische Strenge mit modernen Publikationspraktiken, um die Wirkung Ihrer Forschung zu maximieren.",
    "features.openAccess.title": "Open Access",
    "features.openAccess.description": "Alle Artikel weltweit frei zugänglich ohne Abonnementbarrieren.",
    "features.peerReview.title": "Rigoroses Peer-Review",
    "features.peerReview.description": "Expertengeführtes doppelblindes Peer-Review für höchste Qualitätsstandards.",
    "features.rapidPublication.title": "Schnelle Veröffentlichung",
    "features.rapidPublication.description": "Effizienter Redaktionsprozess mit schneller Bearbeitung von der Einreichung bis zur Veröffentlichung.",
    "features.editorialBoard.title": "Internationaler Redaktionsbeirat",
    "features.editorialBoard.description": "Angesehene Wissenschaftler von führenden Institutionen weltweit.",
    
    // Open Access Models
    "oaModels.title": "Open-Access-Veröffentlichung",
    "oaModels.subtitle": "Publikationsmodell",
    "oaModels.description": "Wir veröffentlichen Open-Access-Zeitschriften mit sofortiger, dauerhafter Verfügbarkeit unter Creative-Commons-Lizenzen.",
    "oaModels.gold.title": "Gold Open Access",
    "oaModels.gold.description": "Alle Artikel sind unmittelbar und dauerhaft unter einer Creative-Commons-Lizenz kostenlos zugänglich.",
    "oaModels.hybrid.title": "Creative-Commons-Lizenzierung",
    "oaModels.hybrid.description": "Klare Nutzungsrechte durch Standardlizenzen (z.B. CC BY 4.0) für maximale Verbreitung und Wirkung.",
    "oaModels.learnMore": "Mehr über unsere OA-Richtlinie",
    "oaModels.accessible": "Forschung für alle zugänglich machen",
    "oaModels.fromMainz": "Forscher weltweit verbinden",
    
    // CTA Section
    "cta.title": "Bereit, Ihre Forschung zu teilen?",
    "cta.subtitle": "Schließen Sie sich Forschern weltweit an, die Scholarly Open vertrauen, um ihre Arbeit mit Integrität und Wirkung zu veröffentlichen.",
    "cta.submit": "Manuskript einreichen",
    "cta.guidelines": "Autorenrichtlinien",
    
    // Footer
    "footer.journals": "Zeitschriften",
    "footer.forAuthors": "Für Autoren",
    "footer.aboutUs": "Über uns",
    "footer.policies": "Richtlinien",
    "footer.copyright": "Scholarly Open i.G. Alle Rechte vorbehalten.",
    "footer.ccbyStatement": "Alle Inhalte werden unter CC BY 4.0 veröffentlicht.",
    "footer.privacy": "Datenschutz",
    "footer.impressum": "Impressum",
    "footer.archiving": "Archivierung & Indexierung",
    
    // Compliance
    "compliance.title": "Compliance & Standards",
    "compliance.doaj": "DOAJ-Richtlinien",
    "compliance.cope": "Publikationsethik (COPE)",
    "compliance.crossref": "CrossRef-Mitglied",
    "compliance.ccby": "CC-BY-4.0-Lizenz",
    "compliance.issn": "ISSN-registriert",
    "compliance.oaspa": "OASPA-Mitglied",
    
    // Editorial Board
    "editorial.title": "Redaktionsbeirat",
    "editorial.subtitle": "Unser angesehener Redaktionsbeirat besteht aus führenden Wissenschaftlern renommierter Institutionen weltweit und gewährleistet höchste Standards bei Peer-Review und redaktioneller Exzellenz.",
    "editorial.editorInChief": "Chefredakteur",
    "editorial.seniorEditors": "Leitende Redakteure",
    "editorial.seniorEditorsSubtitle": "Unsere leitenden Redakteure leiten die redaktionelle Ausrichtung für jede unserer Kerndisziplinen.",
    "editorial.boardMembers": "Redaktionsbeiratsmitglieder",
    "editorial.boardMembersSubtitle": "Unsere Redaktionsbeiratsmitglieder bringen vielfältige Expertise von Institutionen weltweit mit.",
    "editorial.joinTeam": "Werden Sie Teil unseres Redaktionsteams",
    "editorial.joinTeamSubtitle": "Wir suchen stets angesehene Wissenschaftler für unseren Redaktionsbeirat. Wenn Sie an der Förderung offenen Zugangs interessiert sind, würden wir gerne von Ihnen hören.",
    "editorial.expressInterest": "Interesse bekunden",
    "editorial.discipline.socialSciences": "Sozial- & Geisteswissenschaften",
    "editorial.discipline.archaeology": "Archäologie",
    "editorial.discipline.medicalSciences": "Medizinische Wissenschaften",
    "editorial.editorInChief.role": "Chefredakteurin",
    "editorial.editorInChief.specialization": "Sozialwissenschaften & Forschungsmethodik",
    "editorial.senior1.role": "Leitender Redakteur, Sozial- & Geisteswissenschaften",
    "editorial.senior1.specialization": "Politikwissenschaft & Internationale Beziehungen",
    "editorial.senior2.role": "Leitende Redakteurin, Archäologie",
    "editorial.senior2.specialization": "Klassische Archäologie & Kulturerbe",
    "editorial.senior3.role": "Leitender Redakteur, Medizinische Wissenschaften",
    "editorial.senior3.specialization": "Öffentliche Gesundheit & Epidemiologie",
    "editorial.member.soc1.specialization": "Soziologie & Sozialpolitik",
    "editorial.member.soc2.specialization": "Wirtschaftswissenschaften & Entwicklungsstudien",
    "editorial.member.soc3.specialization": "Psychologie & Verhaltenswissenschaften",
    "editorial.member.soc4.specialization": "Anthropologie & Migrationsstudien",
    "editorial.member.arc1.specialization": "Prähistorische Archäologie",
    "editorial.member.arc2.specialization": "Archäologische Wissenschaft & Datierungsmethoden",
    "editorial.member.arc3.specialization": "Nahöstliche Archäologie",
    "editorial.member.arc4.specialization": "Mittelalterliche Archäologie",
    "editorial.member.med1.specialization": "Klinische Medizin & Diagnostik",
    "editorial.member.med2.specialization": "Infektionskrankheiten",
    "editorial.member.med3.specialization": "Biomedizinische Forschung",
    "editorial.member.med4.specialization": "Pharmazeutische Wissenschaften",
    
    // About Page
    "about.title": "Über Scholarly Open",
    "about.subtitle": "Scholarly Open ist ein internationaler Open-Access-Verlag, der sich der Förderung von Wissen durch rigoroses Peer-Review und offenen Zugang verschrieben hat.",
    
    // Contact
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Nehmen Sie Kontakt mit unserem Redaktionsteam auf.",
    
    // Articles
    "articles.title": "Artikel",
    "articles.latest": "Neueste Artikel",    "articles.sampleTitle": "Beispielartikel",
    "articles.sampleNote": "Diese Artikelangaben dienen als illustrative Beispiele für den Start unserer Zeitschriften.",    "articles.viewAll": "Alle Artikel anzeigen",
    "articles.readMore": "Weiterlesen",
    "articles.published": "Veröffentlicht",
    "articles.doi": "DOI",
    "articles.keywords": "Schlagwörter",
    "articles.abstract": "Zusammenfassung",
    "articles.fullText": "Volltext",
    "articles.pdf": "PDF herunterladen",
    "articles.cite": "Zitieren",
    
    // Journal Page
    "journal.about": "Über diese Zeitschrift",
    "journal.aboutText": "Scholarly Open veröffentlicht hochrelevante und FAIR-konforme Forschung in allen unseren Zeitschriften. Wir konzentrieren uns auf transparente Prozesse, schnelle Verbreitung und starke Unterstützung für Autoren.",
    "journal.scope": "Ziele & Reichweite",
    "journal.sections": "Zeitschriftenrubriken",
    "journal.submitTo": "Einreichen bei",
    "journal.submitText": "Bitte lesen Sie unsere Autorenrichtlinien und bereiten Sie Ihr Manuskript gemäß unseren Einreichungsanforderungen vor. Wir begrüßen Originalarbeiten, Reviews und methodische Beiträge, die das FAIR-Wissenschaftsprinzip unterstützen.",
    "journal.startSubmission": "Einreichung starten",
    
    // About Page Content
    "about.heroTitle": "Über Scholarly Open",
    "about.heroSubtitle": "Wir sind ein internationaler Open-Access-Verlag, der sich dafür einsetzt, die wissenschaftliche Kommunikation durch innovative Publikationspraktiken und ein unerschütterliches Engagement für die Integrität der Forschung voranzutreiben.",
    "about.ourMission": "Unsere Mission",
    "about.missionTitle": "Wissen demokratisieren",
    "about.missionP1": "Unsere Mission ist es, die weltweite Verbreitung hochwertiger Forschung durch den offenen Zugang zu peer-reviewed wissenschaftlichen Artikeln zu erleichtern. Wir glauben, dass Wissen nicht durch finanzielle oder geografische Barrieren eingeschränkt werden sollte.",
    "about.missionP2": "Wir arbeiten mit Forschern, Institutionen und Geldgebern weltweit zusammen, um sicherzustellen, dass wichtige Entdeckungen in den Bereichen Künstliche Intelligenz, Klinische Medizin, Nachhaltigkeit, Data Science und Ingenieurwesen die Zielgruppen erreichen, die sie am dringendsten benötigen.",
    "about.ourVision": "Unsere Vision",
    "about.visionTitle": "Eine offenere Zukunft",
    "about.visionP1": "Wir visionieren eine Welt, in der die gesamte wissenschaftliche Forschung frei zugänglich ist, in der Forscher für ihre Beiträge anerkannt werden und in der der Fortschritt des menschlichen Wissens allen gleichermaßen zugutekommt.",
    "about.visionP2": "Durch kontinuierliche Innovation bei Publikationstechnologien und -prozessen streben wir danach, ein nachhaltiges und gerechtes Publikations-Ökosystem zu schaffen, das der globalen Forschungsgemeinschaft dient.",
    
    "about.valuesTitle": "Unsere Grundwerte",
    "about.valuesSub": "Diese Prinzipien leiten alles, was wir bei Scholarly Open tun.",
    "about.value1.title": "Integrität",
    "about.value1.desc": "Wir wahren die höchsten ethischen Standards im wissenschaftlichen Publizieren und gewährleisten Transparenz und Rechenschaftspflicht in all unseren Prozessen.",
    "about.value2.title": "Offenheit",
    "about.value2.desc": "Wir glauben, dass Wissen für alle frei zugänglich sein sollte, und bauen Barrieren für wissenschaftliche und akademische Informationen ab.",
    "about.value3.title": "Exzellenz",
    "about.value3.desc": "Wir verpflichten uns, nur qualitativ hochwertigste Forschung durch strenges Peer-Review und redaktionelle Aufsicht zu veröffentlichen.",
    "about.value4.title": "Globale Wirkung",
    "about.value4.desc": "Wir verbinden Forscher über Grenzen hinweg und fördern die internationale Zusammenarbeit und den Wissensaustausch.",

    "about.journeyTitle": "Unsere Reise",
    "about.journeySub": "Scholarly Open ist eine neue Publikationsinitiative. Wir bauen derzeit unser Zeitschriftenportfolio auf, verfeinern unsere Prozesse und bereiten unsere ersten Open-Access-Publikationen vor.",
    "about.time1.title": "Gründung",
    "about.time1.desc": "Scholarly Open wurde mit einer Vision zur Transformation des wissenschaftlichen Publizierens gegründet.",
    "about.time2.title": "Unser Team aufbauen",
    "about.time2.desc": "Wir haben ein Redaktionsteam, einen Beirat und Verlagspartner zusammengestellt, um unser Zeitschriftenportfolio auf den Weg zu bringen.",
    "about.time3.title": "Workflows entwickeln",
    "about.time3.desc": "Wir etablieren FAIR-Workflows, Open-Access-Prozesse und Systeme zur Unterstützung von Autoren.",
    "about.time4.title": "Vorbereitung auf den Launch",
    "about.time4.desc": "Unsere ersten Zeitschriften werden für die Veröffentlichung vorbereitet, Compliance- und Indexierungsbemühungen sind im Gange.",

    "about.reachTitle": "Forschern weltweit dienen",
    "about.reachP1": "Scholarly Open widmet sich der Verbindung von Forschern auf der ganzen Welt. Wir arbeiten mit Autoren, Gutachtern und Institutionen aus allen Kontinenten zusammen, um die wissenschaftliche Kommunikation voranzutreiben.",
    "about.reachP2": "Unser internationaler Redaktionsbeirat und unser globales Netzwerk von Peer-Reviewern stellen sicher, dass Forschung aus allen Regionen die Aufmerksamkeit und strenge Bewertung erhält, die sie verdient.",
    "about.communityTitle": "Treten Sie unserer Gemeinschaft bei",
    "about.communitySub": "Ob als Autor, Gutachter oder Mitglied des Redaktionsbeirats – wir begrüßen Ihre Teilnahme an der Förderung der offenen Wissenschaft.",
    "about.communitySubmit": "Ihre Forschung einreichen",
    
    // Contact Page Content
    "contact.heroTitle": "Kontaktieren Sie uns",
    "contact.heroSubtitle": "Haben Sie Fragen zur Einreichung Ihrer Forschung, zu unserem Peer-Review-Verfahren oder zu unseren Open-Access-Richtlinien? Unser Team hilft Ihnen gerne weiter.",
    "contact.info.general": "Allgemeine Anfragen",
    "contact.info.editorial": "Redaktionsbüro",
    "contact.info.submissions": "Einreichungen",
    "contact.info.address": "Adresse",
    "contact.info.headquarters": "Hauptsitz",
    "contact.info.phone": "Hauptbüro",
    "contact.info.hours": "Bürozeiten",
    "contact.info.weekday": "Montag - Freitag",
    "contact.info.weekend": "Samstag - Sonntag",
    "contact.info.weekendVal": "Geschlossen",
    
    "contact.deptsTitle": "Abteilungskontakte",
    "contact.deptsSub": "Für eine schnellere Antwort wenden Sie sich bitte direkt an die entsprechende Abteilung.",
    "contact.dept1.desc": "Für manuskriptbezogene Anfragen, Fragen zum Peer-Review und redaktionelle Entscheidungen.",
    "contact.dept2.desc": "Für Unterstützung bei der Einreichung, Formatierungsfragen und Autorenrichtlinien.",
    "contact.dept3.name": "Finanzen & APCs",
    "contact.dept3.desc": "Für Rechnungen, Zahlungsanfragen und Anträge auf APC-Erlass.",
    "contact.dept4.name": "Technischer Support",
    "contact.dept4.desc": "Für Website-Probleme, Störungen des Einreichungssystems und technische Fragen.",
    "contact.dept5.name": "Forschungsintegrität & Ethik",
    "contact.dept5.desc": "Zur Meldung von ethischen Bedenken, Plagiatsvorwürfen oder Fragen der Publikationsintegrität.",

    "contact.form.title": "Senden Sie uns eine Nachricht",
    "contact.form.subtitle": "Füllen Sie das folgende Formular aus und wir werden uns innerhalb von 1-2 Werktagen bei Ihnen melden.",
    "contact.form.faqHeader": "Bevor Sie uns kontaktieren, finden Sie Antworten möglicherweise in:",
    "contact.faq.ethicsDesc": "Einhaltung von COPE-Richtlinien, Standards zur Forschungsintegrität und Meldung ethischer Bedenken.",
    "contact.form.cardTitle": "Kontaktformular",
    "contact.form.cardSub": "Alle mit * gekennzeichneten Felder sind Pflichtfelder.",
    "contact.form.sentTitle": "Nachricht gesendet",
    "contact.form.sentDesc": "Vielen Dank für Ihre Kontaktaufnahme. Wir werden Ihnen innerhalb von 1-2 Werktagen antworten.",
    "contact.form.sentButton": "Eine weitere Nachricht senden",
    
    "contact.form.labelName": "Vollständiger Name *",
    "contact.form.labelEmail": "E-Mail-Adresse *",
    "contact.form.labelAffiliation": "Institution / Organisation",
    "contact.form.labelSubject": "Betreff *",
    "contact.form.labelMessage": "Nachricht *",
    
    "contact.form.optDefault": "Wählen Sie einen Betreff",
    "contact.form.optSubmission": "Manuskript-Einreichung",
    "contact.form.optReview": "Status der Peer-Review",
    "contact.form.optAPC": "APC / Zahlung",
    "contact.form.optTechnical": "Technisches Problem",
    "contact.form.optEditorial": "Redaktionsbeirat",
    "contact.form.optEthics": "Fragen zur Forschungsintegrität & Ethik",
    "contact.form.optPartner": "Partnerschaft / Zusammenarbeit",
    "contact.form.optOther": "Sonstiges",
    
    "contact.form.privacyConsent": "Ich willige in die Verarbeitung meiner personenbezogenen Daten zum Zwecke der Bearbeitung meiner Anfrage ein.",
    "contact.form.privacyRead": "Ich habe die",
    "contact.form.buttonSend": "Nachricht senden",
    "contact.form.buttonSending": "Wird gesendet...",
    
    "contact.map.title": "Globale Reichweite",
    "contact.map.subtitle": "Scholarly Open dient Forschern weltweit und verbindet Wissenschaftler über alle Kontinente hinweg.",
    "contact.map.basedIn": "Sitz in Mainz, Deutschland",

    // Guidelines Page Extra
    "guidelines.heroTitle": "Autorenrichtlinien",
    "guidelines.heroSubtitle": "Umfassende Anweisungen zur Vorbereitung Ihres Manuskripts für die Einreichung bei den Zeitschriften von Scholarly Open. Die Einhaltung dieser Richtlinien trägt zu einem reibungslosen Begutachtungsprozess in den Sozial- & Geisteswissenschaften, der Medizin und anderen fachspezifischen Zeitschriften bei.",
    "guidelines.downloadTemplate": "Vorlage herunterladen",
    "guidelines.beforeSubmit": "Vor der Einreichung",
    "guidelines.beforeSubmitSub": "Bitte stellen Sie vor der Einreichung sicher, dass Ihre Arbeit diesen Anforderungen entspricht.",
    "guidelines.originalWork": "Originalarbeit",
    "guidelines.originalWorkDesc": "Das Manuskript muss im Original vorliegen und darf nicht anderweitig geprüft werden. Plagiatsprüfungen werden durchgeführt.",
    "guidelines.authorAgreement": "Autorenvereinbarung",
    "guidelines.authorAgreementDesc": "Alle Autoren müssen der Einreichung zustimmen und die Autorenschaftskriterien des ICMJE erfüllen.",
    "guidelines.ethicsApproval": "Ethikfreigabe",
    "guidelines.ethicsApprovalDesc": "Forschungen an Menschen oder Tieren müssen über eine entsprechende Ethikfreigabe verfügen.",
    "guidelines.conflictOfInterest": "Interessenkonflikt",
    "guidelines.conflictOfInterestDesc": "Alle potenziellen Interessenkonflikte müssen im Manuskript offengelegt werden.",

    // APC Page
    "apc.heroSubtitle": "Transparente Preisgestaltung für Open-Access-Publikationen. Wir bieten wettbewerbsfähige APCs mit Gebührenerlass-Programmen, um sicherzustellen, dass Forschungen aus allen Bereichen veröffentlicht werden können.",
    "apc.understandingTitle": "APCs verstehen",
    "apc.understandingDesc": "Article Processing Charges (APCs) sind Gebühren, die Autoren oder deren Institutionen in Rechnung gestellt werden, um die Kosten der Open-Access-Veröffentlichung zu decken. APCs ermöglichen es uns, Artikel für Leser weltweit frei verfügbar zu machen und gleichzeitig hohe redaktionelle und produktionsbezogene Standards aufrechtzuerhalten.",
    "apc.chargedTitle": "Wann wird die APC in Rechnung gestellt?",
    "apc.chargedDesc": "APCs werden erst in Rechnung gestellt, nachdem Ihr Manuskript nach dem Peer-Review zur Veröffentlichung angenommen wurde. Es fallen keine Einreichungs- oder Begutachtungsgebühren an.",
    "apc.coversTitle": "Was deckt die APC ab?",
    "apc.coversDesc": "Die APC deckt das Peer-Review-Management, das Lektorat, den Satz, die DOI-Registrierung, das Hosting, die Archivierung und die dauerhafte Barrierefreiheit ab.",
    "apc.whoPaysTitle": "Wer bezahlt die APC?",
    "apc.whoPaysDesc": "APCs können von Autoren, deren Institutionen, Forschungsförderern oder im Rahmen von institutionellen Vereinbarungen bezahlt werden. Viele Förderer erkennen APCs als förderfähige Forschungskosten an.",
    "apc.currentRatesTitle": "Aktuelle APC-Gebühren",
    "apc.currentRatesDesc": "Unsere APCs variieren je nach Fachbereich, um die unterschiedlichen Kosten und Dienstleistungen widerzuspiegeln. Diese Tarife gelten für unser gesamtes Portfolio der sieben Scholarly Open-Zeitschriften.",
    "apc.perArticle": "pro Artikel",
    "apc.vatNotice": "Alle Preise verstehen sich exklusive Mehrwertsteuer, wo anwendbar. Institutionelle Vereinbarungen können abweichende Sätze vorsehen.",
    "apc.waiversTitle": "Gebührenerlass & Rabatte",
    "apc.waiversDesc": "Wir setzen uns dafür ein, Open-Access-Publizieren für Forscher weltweit zugänglich zu machen, unabhängig von ihrer finanziellen Situation.",
    "apc.applyWaiverTitle": "So beantragen Sie einen Gebührenerlass",
    "apc.applyWaiverDesc": "Anträge auf Gebührenerlass sollten zum Zeitpunkt der Einreichung über unser Online-Einreichungssystem gestellt werden. Bitte machen Sie Angaben zu Ihrer Finanzierungssituation und Ihrer Eignungskategorie. Entscheidungen über den Gebührenerlass werden unabhängig von redaktionellen Entscheidungen getroffen und haben keinen Einfluss auf das Peer-Review-Verfahren.",
    "apc.paymentTitle": "Zahlungsmethoden",
    "apc.paymentDesc": "Wir bieten flexible Zahlungsoptionen an, um unterschiedliche institutionelle Anforderungen zu berücksichtigen.",
    "apc.creditCard": "Kreditkarte",
    "apc.creditCardDesc": "Visa, Mastercard und American Express werden über unser sicheres Zahlungsportal akzeptiert.",
    "apc.bankTransfer": "Banküberweisung",
    "apc.bankTransferDesc": "Rechnungszahlung per SEPA- oder internationaler Banküberweisung. Bankdaten werden nach Annahme des Manuskripts mitgeteilt.",
    "apc.instAgreements": "Institutionelle Vereinbarungen",
    "apc.instAgreementsDesc": "Prüfen Sie, ob Ihre Institution eine Vereinbarung mit uns für eine zentralisierte Abrechnung getroffen hat.",
    "apc.complianceTitle": "Förderer-Compliance",
    "apc.complianceDesc": "Unsere Open-Access-Richtlinien entsprechen den Anforderungen der wichtigsten Forschungsförderer.",
    "apc.questionsTitle": "Fragen zu den Gebühren?",
    "apc.questionsDesc": "Unser Team berät Sie gerne zu Zahlungsmöglichkeiten, Gebührenerlassen oder institutionellen Vereinbarungen.",

    // Open Access Page
    "openaccess.heroSubtitle": "Scholarly Open setzt sich für Open-Access-Publizieren ein. Wir glauben, dass wissenschaftliches Wissen für jeden und überall frei verfügbar sein sollte, um die Forschung zu beschleunigen und der Gesellschaft zu nützen.",
    "openaccess.aboutOATitle": "Über Open Access",
    "openaccess.aboutOASubtitle": "Wissen ohne Barrieren",
    "openaccess.aboutOAP1": "Open Access (OA) bedeutet, dass Forschungsergebnisse kostenlos und frei von den meisten urheberrechtlichen und lizenzrechtlichen Einschränkungen online verbreitet werden. Jeder kann den Volltext dieser Artikel lesen, herunterladen, kopieren, verbreiten, drucken, durchsuchen oder darauf verlinken.",
    "openaccess.aboutOAP2": "Wir unterstützen die Prinzipien der Budapester Open-Access-Initiative (2002) und sind davon überzeugt, dass die Beseitigung von Zugangsbarrieren zu wissenschaftlicher Literatur die Forschung beschleunigt, die Bildung bereichert und neue Formen der Zusammenarbeit ermöglicht.",
    "openaccess.freeToRead": "Frei zu lesen",
    "openaccess.freeToReuse": "Frei zur Wiederverwendung",
    "openaccess.freeToShare": "Frei zum Teilen",
    "openaccess.benefitsTitle": "Vorteile von Open Access",
    "openaccess.benefitsDesc": "Open-Access-Publizieren bietet erhebliche Vorteile für Autoren, Leser und die Gesellschaft.",
    "openaccess.benefit1.title": "Globale Reichweite",
    "openaccess.benefit1.desc": "Open-Access-Artikel erreichen ein breiteres Publikum, darunter Forscher, Praktiker, politische Entscheidungsträger und die breite Öffentlichkeit weltweit.",
    "openaccess.benefit2.title": "Höhere Zitationsraten",
    "openaccess.benefit2.desc": "Studien zeigen, dass Open-Access-Artikel mehr Zitationen erhalten und eine größere Forschungswirkung haben als kostenpflichtige Inhalte.",
    "openaccess.benefit3.title": "Sofortiger Zugang",
    "openaccess.benefit3.desc": "Die Forschung ist sofort nach der Veröffentlichung ohne Sperrfrist verfügbar, was das Tempo des wissenschaftlichen Entdeckens beschleunigt.",
    "openaccess.benefit4.title": "Nutzen für die Öffentlichkeit",
    "openaccess.benefit4.desc": "Öffentlich finanzierte Forschung wird öffentlich zugänglich gemacht, wodurch die gesellschaftliche Rendite der Investitionen in die Wissenschaft maximiert wird.",
    "openaccess.modelTitle": "Unser Open-Access-Modell",
    "openaccess.modelDesc": "Alle Scholarly Open-Zeitschriften nutzen ein Gold-Open-Access-Modell, das sicherstellt, dass jeder Artikel ab dem Zeitpunkt seiner Veröffentlichung frei verfügbar ist.",
    "openaccess.goldBadge": "Standardmodell",
    "openaccess.goldDesc": "Alle Scholarly Open-Zeitschriften veröffentlichen sofort Open Access unter einer Creative-Commons-Lizenz. Der Autor oder seine Institution zahlt eine Artikelbearbeitungsgebühr (APC), um die Publikationskosten zu decken.",
    "openaccess.goldFeature1": "Sofortiger Open Access bei Veröffentlichung",
    "openaccess.goldFeature2": "Standardmäßig unter CC BY 4.0-Lizenz",
    "openaccess.goldFeature3": "Volles Urheberrecht verbleibt beim Autor",
    "openaccess.goldFeature4": "In den wichtigsten Datenbanken indexiert",
    "openaccess.goldFeature5": "Dauerhaft kostenloser Zugang",
    "openaccess.licensingTitle": "Lizenzierung",
    "openaccess.licensingDesc": "Wir nutzen Creative-Commons-Lizenzen, um festzulegen, wie veröffentlichte Inhalte wiederverwendet werden können, und sorgen so für Klarheit für Autoren und Leser.",
    "openaccess.ccbyDefault": "CC BY 4.0 (Standard)",
    "openaccess.ccbyDefaultDesc": "Diese Lizenz erlaubt es anderen, Ihre Arbeit zu verbreiten, zu mischen, anzupassen und darauf aufzubauen, auch kommerziell, solange Sie als Urheber des Originals genannt werden. Dies ist die flexibelste angebotene Lizenz und wird für die maximale Verbreitung empfohlen.",
    "openaccess.ccbync": "CC BY-NC 4.0",
    "openaccess.ccbyncDesc": "Ähnlich wie CC BY, beschränkt die Wiederverwendung jedoch auf nicht-kommerzielle Zwecke. Auf Anfrage unter bestimmten Umständen verfügbar.",
    "openaccess.ccbyncnd": "CC BY-NC-ND 4.0",
    "openaccess.ccbyncndDesc": "Die restriktivste Lizenz, die nur die nicht-kommerzielle Weiterverbreitung ohne Änderungen erlaubt. In Ausnahmefällen verfügbar.",
    "openaccess.rightsTitle": "Autorenrechte",
    "openaccess.rightsDesc": "Bei Scholarly Open behalten Autoren das Urheberrecht an ihrer Arbeit. Das bedeutet für Sie:",
    "openaccess.right1.title": "Urheberrechtserhalt",
    "openaccess.right1.desc": "Autoren behalten das uneingeschränkte Urheberrecht an ihrer Arbeit. Wir bitten lediglich um eine Lizenz zur Veröffentlichung.",
    "openaccess.right2.title": "Selbstarchivierung",
    "openaccess.right2.desc": "Autoren können die veröffentlichte Version sofort nach der Veröffentlichung in institutionellen Repositorien und auf anderen Plattformen hinterlegen.",
    "openaccess.right3.title": "Wiederverwendung",
    "openaccess.right3.desc": "Autoren können ihre Arbeit ohne Einholung einer Erlaubnis in zukünftigen Veröffentlichungen, Präsentationen und Lehrmaterialien wiederverwenden.",
    "openaccess.right4.title": "Rechte Dritter",
    "openaccess.right4.desc": "Für Abbildungen oder Texte aus Quellen Dritter sind die Autoren dafür verantwortlich, die entsprechenden Genehmigungen einzuholen.",
    "openaccess.complianceTitle": "Förderer-Compliance",
    "openaccess.complianceDesc": "Unsere Open-Access-Richtlinien sind so konzipiert, dass sie den Anforderungen der wichtigsten Forschungsförderer entsprechen.",
    "openaccess.complianceNote": "Wenn Ihr Förderer spezifische Anforderungen hat, die hier nicht aufgeführt sind, kontaktieren Sie uns bitte, um Compliance-Optionen zu besprechen.",
    "openaccess.ctaTitle": "Veröffentlichen Sie Open Access mit uns",
    "openaccess.ctaSubtitle": "Schließen Sie sich der Open-Access-Bewegung an und machen Sie Ihre Forschung weltweit frei verfügbar.",
    "openaccess.ctaSubmit": "Ihre Forschung einreichen",
    "openaccess.ctaApc": "APC-Informationen anzeigen",

    // Privacy Page
    "privacy.heroSubtitle": "Diese Datenschutzerklärung erläutert, wie Scholarly Open Ihre personenbezogenen Daten in Übereinstimmung mit der Datenschutz-Grundverordnung (DSGVO) und den deutschen Datenschutzgesetzen erhebt, nutzt und schützt.",
    "privacy.lastUpdated": "Zuletzt aktualisiert: Januar 2024",
    "privacy.controller.title": "1. Verantwortlicher für die Datenverarbeitung",
    "privacy.controller.desc": "Der für die Verarbeitung Ihrer personenbezogenen Daten Verantwortliche ist:",
    "privacy.controller.addr": "Scholarly Open\nInternational Open Access Publisher\nE-Mail: info@scholarlyopen.org",
    "privacy.data.title": "2. Daten, die wir erheben",
    "privacy.data.desc": "Wir erheben und verarbeiten die folgenden Kategorien personenbezogener Daten:",
    "privacy.data.provide.title": "2.1 Daten, die Sie uns bereitstellen",
    "privacy.data.provide.li1": "Name, E-Mail-Adresse und institutionelle Zugehörigkeit bei der Erstellung eines Kontos",
    "privacy.data.provide.li2": "Manuskripteinreichungen und zugehörige Autoreninformationen",
    "privacy.data.provide.li3": "Korrespondenz mit unserem Redaktionsteam",
    "privacy.data.provide.li4": "Zahlungsinformationen für Artikelbearbeitungsgebühren (APCs)",
    "privacy.data.provide.li5": "Gutachten und redaktionelle Mitteilungen",
    "privacy.data.auto.title": "2.2 Automatisch erhobene Daten",
    "privacy.data.auto.li1": "IP-Adresse und Browserinformationen",
    "privacy.data.auto.li2": "Besuchte Seiten und auf unserer Website verbrachte Zeit",
    "privacy.data.auto.li3": "Informationen über die verweisende Website",
    "privacy.data.auto.li4": "Gerätetyp und Betriebssystem",
    "privacy.data.basis.title": "3. Rechtsgrundlage für die Verarbeitung",
    "privacy.data.basis.desc": "Wir verarbeiten Ihre personenbezogenen Daten auf folgenden rechtlichen Grundlagen gemäß DSGVO Artikel 6:",
    "privacy.data.basis.li1": "Vertragserfüllung (Art. 6(1)(b) DSGVO): Verarbeitung, die zur Erfüllung unserer Publikationsdienste erforderlich ist",
    "privacy.data.basis.li2": "Berechtigte Interessen (Art. 6(1)(f) DSGVO): Verbesserung unserer Dienste und Website-Funktionalität",
    "privacy.data.basis.li3": "Rechtliche Verpflichtungen (Art. 6(1)(c) DSGVO): Einhaltung steuerlicher und buchhalterischer Anforderungen",
    "privacy.data.basis.li4": "Einwilligung (Art. 6(1)(a) DSGVO): Marketingmitteilungen und optionale Cookies",
    "privacy.use.title": "4. Wie wir Ihre Daten verwenden",
    "privacy.use.desc": "Ihre personenbezogenen Daten werden für folgende Zwecke verwendet:",
    "privacy.use.li1": "Bearbeitung und Verwaltung von Manuskripteinreichungen",
    "privacy.use.li2": "Kommunikation über das Peer-Review-Verfahren",
    "privacy.use.li3": "Veröffentlichung von Artikeln und Pflege des wissenschaftlichen Registers",
    "privacy.use.li4": "Bearbeitung von Zahlungen und Ausstellung von Rechnungen",
    "privacy.use.li5": "Senden von dienstbezogenen Benachrichtigungen",
    "privacy.use.li6": "Verbesserung unserer Website und Dienste",
    "privacy.use.li7": "Einhaltung gesetzlicher und regulatorischer Anforderungen",
    "privacy.sharing.title": "5. Weitergabe von Daten",
    "privacy.sharing.desc": "Wir können Ihre personenbezogenen Daten an folgende Stellen weitergeben:",
    "privacy.sharing.li1": "Peer-Reviewer: Anonymisierte Manuskriptinhalte zur Begutachtung",
    "privacy.sharing.li2": "Indexierungsdienste: Metadaten veröffentlichter Artikel",
    "privacy.sharing.li3": "Zahlungsabwickler: Für eine sichere Zahlungsabwicklung",
    "privacy.sharing.li4": "Dienstleister: Hosting-, E-Mail- und Analysedienste",
    "privacy.sharing.li5": "Gesetzliche Behörden: Wenn gesetzlich vorgeschrieben",
    "privacy.sharing.noSell": "Wir verkaufen Ihre personenbezogenen Daten nicht an Dritte.",
    "privacy.transfers.title": "6. Internationale Datentransfers",
    "privacy.transfers.desc": "Einige unserer Dienstleister befinden sich möglicherweise außerhalb des Europäischen Wirtschaftsraums (EWR). Wenn wir Daten außerhalb des EWR übertragen, stellen wir sicher, dass angemessene Garantien vorhanden sind, einschließlich:",
    "privacy.transfers.li1": "EU-Standardvertragsklauseln",
    "privacy.transfers.li2": "Angemessenheitsbeschlüsse der Europäischen Kommission",
    "privacy.transfers.li3": "Verbindliche interne Datenschutzvorschriften (Binding Corporate Rules)",
    "privacy.retention.title": "7. Datenaufbewahrung",
    "privacy.retention.desc": "Wir bewahren Ihre personenbezogenen Daten so lange auf, wie es zur Erfüllung der Zwecke, für die sie erhoben wurden, erforderlich ist:",
    "privacy.retention.li1": "Veröffentlichte Artikel: Dauerhaft (Teil des wissenschaftlichen Registers)",
    "privacy.retention.li2": "Kontoinformationen: Dauer des Bestehens des Kontos zuzüglich 3 Jahre",
    "privacy.retention.li3": "Abgelehnte Manuskripte: 2 Jahre nach Ablehnung",
    "privacy.retention.li4": "Finanzunterlagen: 10 Jahre (gesetzliche Anforderung nach deutschem Steuerrecht)",
    "privacy.retention.li5": "Website-Analyse: 26 Monate",
    "privacy.rights.title": "8. Ihre Rechte",
    "privacy.rights.desc": "Unter der DSGVO haben Sie folgende Rechte bezüglich Ihrer personenbezogenen Daten:",
    "privacy.rights.li1": "Auskunft: Kopie Ihrer personenbezogenen Daten anfordern",
    "privacy.rights.li2": "Berichtigung: Korrektur unrichtiger oder unvollständiger Daten verlangen",
    "privacy.rights.li3": "Löschung: Löschung Ihrer Daten verlangen (mit Einschränkungen)",
    "privacy.rights.li4": "Einschränkung: Einschränkung der Verarbeitung Ihrer Daten verlangen",
    "privacy.rights.li5": "Datenübertragbarkeit: Daten in einem strukturierten Format erhalten",
    "privacy.rights.li6": "Widerspruch: Widerspruch gegen die Verarbeitung aufgrund berechtigter Interessen einlegen",
    "privacy.rights.li7": "Einwilligung widerrufen: Soweit die Verarbeitung auf einer Einwilligung beruht",
    "privacy.rights.contact": "Um diese Rechte auszuüben, kontaktieren Sie uns bitte unter privacy@scholarlyopen.org.",
    "privacy.cookies.title": "9. Cookies",
    "privacy.cookies.desc1": "Wir verwenden Cookies und ähnliche Technologien auf unserer Website. Essenzielle Cookies sind für das Funktionieren der Website erforderlich. Analyse- und Einstellungs-Cookies werden nur mit Ihrer Einwilligung verwendet.",
    "privacy.cookies.desc2": "Sie können Ihre Cookie-Präferenzen über unser Cookie-Banner oder Ihre Browsereinstellungen verwalten.",
    "privacy.security.title": "10. Sicherheit",
    "privacy.security.desc": "Wir implementieren angemessene technische und organisatorische Maßnahmen zum Schutz Ihrer personenbezogenen Daten, einschließlich:",
    "privacy.security.li1": "Verschlüsselung der Daten bei der Übertragung und im Ruhezustand",
    "privacy.security.li2": "Zugriffskontrollen und Authentifizierung",
    "privacy.security.li3": "Regelmäßige Sicherheitsbewertungen",
    "privacy.security.li4": "Schulung der Mitarbeiter zum Datenschutz",
    "privacy.complaints.title": "11. Beschwerden",
    "privacy.complaints.desc": "Wenn Sie der Meinung sind, dass wir Ihre personenbezogenen Daten nicht korrekt verarbeitet haben, haben Sie das Recht, eine Beschwerde bei einer Aufsichtsbehörde in Ihrer Gerichtsbarkeit einzureichen. Bitte kontaktieren Sie uns unter privacy@scholarlyopen.org und wir helfen Ihnen bei der Identifizierung der zuständigen Behörde.",
    "privacy.changes.title": "12. Änderungen dieser Richtlinie",
    "privacy.changes.desc": "Wir können diese Datenschutzerklärung von Zeit zu Zeit aktualisieren. Wir werden Sie über wesentliche Änderungen informieren, indem wir einen Hinweis auf unserer Website veröffentlichen oder Ihnen eine E-Mail senden.",
    "privacy.contact.title": "13. Kontaktieren Sie uns",
    "privacy.contact.desc": "Wenn Sie Fragen zu dieser Datenschutzerklärung oder unseren Datenpraktiken haben, wenden Sie sich bitte an:",
    "privacy.contact.addr": "Datenschutzbeauftragter\nScholarly Open\nE-Mail: info@scholarlyopen.org",

    // Impressum Page
    "impressum.heroSubtitle": "Rechtliche Hinweise gemäß § 5 TMG (Telemediengesetz) und § 55 RStV (Rundfunkstaatsvertrag).",
    "impressum.warningTitle": "Gründungsphase (i.G.) / Founding Phase",
    "impressum.warningDesc1": "Scholarly Open befindet sich derzeit in der Gründungsphase (in Gründung / i.G.). Die formelle Eintragung ins Handelsregister sowie die Beantragung der Umsatzsteuer-Identifikationsnummer erfolgen nach Abschluss der organisatorischen Aufbauphase. Bis zur vollständigen Registrierung sind die unten genannten Personen gemeinsam verantwortlich.",
    "impressum.warningDesc2": "Scholarly Open is currently in the founding phase (in Gründung / i.G.). Formal registration in the commercial register and application for the VAT identification number will take place after the organizational setup phase is completed. Until full registration, the persons named below are jointly responsible for the content.",
    "impressum.tmgTitle": "Angaben gemäß § 5 TMG",
    "impressum.tmgCompany": "Scholarly Open i.G.",
    "impressum.tmgPhase": "(in Gründung / under formation)",
    "impressum.tmgPub": "International Open Access Publisher",
    "impressum.ownersTitle": "Verantwortliche Personen / Responsible Persons",
    "impressum.ownerRole": "Inhaber und verantwortlich für den gesamten Inhalt",
    "impressum.ownerRoleSub": "(Owner and responsible for all content)",
    "impressum.contactTitle": "Kontakt / Contact",
    "impressum.contactEmail": "E-Mail:",
    "impressum.contactWebsite": "Website:",
    "impressum.statusTitle": "Registrierungsstatus / Registration Status",
    "impressum.statusHR": "Handelsregistereintragung:",
    "impressum.statusHRSub": "In Vorbereitung. Die Eintragung erfolgt nach Abschluss der Gründungsphase. (Commercial register entry: In preparation. Registration will be completed after the founding phase.)",
    "impressum.statusVat": "Umsatzsteuer-ID:",
    "impressum.statusVatSub": "Wird nach der Gewerbeanmeldung beim zuständigen Finanzamt beantragt. (VAT ID: Will be applied for at the responsible tax office after business registration.)",
    "impressum.rstvTitle": "Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV",
    "impressum.disputeTitle": "EU-Streitschlichtung",
    "impressum.disputeDesc1": "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:",
    "impressum.disputeDesc2": "Unsere E-Mail-Adresse finden Sie oben im Impressum.",
    "impressum.consumerTitle": "Verbraucherstreitbeilegung / Universalschlichtungsstelle",
    "impressum.consumerDesc": "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.",
    "impressum.liabContentTitle": "Haftung für Inhalte",
    "impressum.liabContentDesc1": "Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.",
    "impressum.liabContentDesc2": "Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.",
    "impressum.liabLinksTitle": "Haftung für Links",
    "impressum.liabLinksDesc1": "Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.",
    "impressum.liabLinksDesc2": "Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.",
    "impressum.copyrightTitle": "Urheberrecht",
    "impressum.copyrightDesc1": "Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.",
    "impressum.copyrightDesc2": "Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.",
    "impressum.copyrightDesc3": "Hinweis: Die in unseren Zeitschriften veröffentlichten Artikel unterliegen den jeweiligen Creative Commons Lizenzen und können entsprechend der Lizenzbedingungen weiterverwendet werden.",

    // Language Toggle
    "language.en": "English",
    "language.de": "Deutsch",
  },
} as const

// Default translation function for SSR
const defaultT = (key: string): string => {
  const keys = translations.en as Record<string, string>
  return keys[key] || key
}

// Default context value for SSR
const defaultContextValue: LanguageContextType = {
  language: "en",
  setLanguage: () => {},
  t: defaultT,
}

const LanguageContext = createContext<LanguageContextType>(defaultContextValue)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    if (typeof window !== "undefined") {
      const hostname = window.location.hostname
      const pathname = window.location.pathname
      const search = window.location.search
      const port = window.location.port ? `:${window.location.port}` : ""

      const isDeDomain = hostname.endsWith(".de")
      const isLocalDeSim = hostname === "localhost.de"

      if (isDeDomain || isLocalDeSim) {
        // Option A: Automatically intercept `.de` / `localhost.de` access,
        // set preferred language to German, and redirect to the unified .org / localhost domain
        localStorage.setItem("scholarly-open-language", "de")
        
        const targetHost = isLocalDeSim ? "localhost" : "scholarlyopen.org"
        const protocol = isLocalDeSim ? "http" : "https"
        
        window.location.replace(`${protocol}://${targetHost}${port}${pathname}${search}`)
      } else {
        const stored = localStorage.getItem("scholarly-open-language") as Language
        if (stored && (stored === "en" || stored === "de")) {
          setLanguageState(stored)
        } else {
          setLanguageState("en")
        }
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("scholarly-open-language", lang)
  }

  const t = (key: string): string => {
    const keys = translations[language] as Record<string, string>
    return keys[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

